from random import randrange

pub = {0:"	Ackhorne, The (9 St. Martins Lane)",
1:"Agar Arms, The (Common Lane)",
2:"Ainsty, The (59 Boroughbridge Road)",
3:"Aldwark Arms (Rice Lane)",
4:"Alice Hawthorn, The (The Green)",
5:"All Bar One (13-17 New Street)",
6:"Anchor Inn (Langthorpe)",
7:"Anchor Inn (New Road)",
8:"Angel On The Green (2 Bishopthorpe Rd)",
9:"Angel, The (Market Place)",
10:"Applejack's (1 Tower Street)",
11:"Artful Dodger Bar, The (47 Micklegate)",
12:"Banyan Bar (3 Little Stonegate)",
13:"Bay Horse (55 Blossom Street)",
14:"Bay Horse Inn (75 Market Place)",
15:"Bay Horse, The (105 Main Street)",
16:"Bay Horse, The (6 Main Street)",
17:"Bay Horse, The (York Road)",
18:"Bay Tree, The (Main Street)",
19:"Beach House, The (71-73 Market Street)",
20:"Beagle, The (169 Foxwood Lane)",
21:"Beeswing Ale House, The (55 Hull Road)",
22:"Biltmore, The (29 Swinegate)",
23:"Bishopthorpe Social Club (12 Main Street)",
24:"Bistro Guy (40 Gillygate)",
25:"Black Bull (18 Market Place)",
26:"Black Bull (Hull Road)",
27:"Black Bull, The (6 St James Square)",
28:"Black Bull, The (Main Street)",
29:"Black Horse (42-44 The Village)",
30:"Black Horse, The (29 Monkgate)",
31:"Black Horse, The (Newton Road)",
32:"Black Horse, The (Seaton Ross)",
33:"Black Swan Hotel (Market Place)",
34:"Black Swan, The (11 Market Place)",
35:"Black Swan, The (Peasholme Green)",
36:"Blacksmiths Arms (79 High Street)",
37:"Blacksmiths Arms (Front Street)",
38:"Blacksmiths Arms (Main Street)",
39:"Blacksmith's Arms, The (56 The Old Village)",
40:"Blacksmiths Arms, The (Cherry Tree Avenue)",
41:"Blacksmiths Arms, The (Farlington)",
42:"Blacksmiths Arms, The (Westow Croft Main Street)",
43:"Blue Bell Inn, The (Leeming Lane)",
44:"Blue Bell, The (53 Fossgate)",
45:"Blue Boar (5 Castlegate)",
46:"Bluebell Country Inn, The (Main Street)",
47:"Bobo Lobo (5 Little Stonegate)",
48:"Bohemian Bar, The (Spark, 17-21 Piccadilly)",
49:"Boot & Shoe Inn, The (Main Street)",
50:"Boot & Shoe Inn, The (Marston Road)",
51:"Boot & Slipper (St. Helens Square)",
52:"Bootham Tavern, The (29 Bootham)",
53:"Bora Bora (5 Back Swinegate)",
54:"Botanist, The (15-19 Stonegate)",
55:"Brew York Beer Hall (Enterprise Complex)",
56:"Brew York Tap Room (Enterprise Complex)",
57:"BrewDog York (130 - 134 Micklegate)",
58:"Brigantes (114 Micklegate)",
59:"Buckles Inn, The (Tadcaster Road)",
60:"Burns Hotel (23 Market Street)",
61:"Burton Stone Inn (34 Clifton)",
62:"Carlton Tavern, The (140 Acomb Road)",
63:"Carpenters Arms (56 Southgate)",
64:"Carpenters Arms, The (Highfield Lane)",
65:"Castle Inn, The (Sheriff Hutton)",
66:"Cave Du Cochon (19 Walmgate)",
67:"Chapter House Bar @ Principal York Hotel (Station Road)",
68:"Charles XII (Main Street)",
69:"Chequers Inn, The (Church Street (Off B1224))",
70:"City Screen (13-17 Coney Street)",
71:"Clifton Hotel, The (Water Lane)",
72:"Clockhouse (Kingsway)",
73:"Coach House Hotel, The (22 Marygate)",
74:"Cock & Bottle, The (61 Skeldergate)",
75:"College Arms (Bielby)",
76:"College Arms (Main Street)",
77:"Commercial (Market Place)",
78:"Corner Pin, The (17 Tanner Row)",
79:"Cosy Club (19-22 Fossgate)",
80:"Cottage Inn (115 The Village)",
81:"Crescent, The (8 The Crescent)",
82:"Crooked Tap, The (39 The Green)",
83:"Cross Keys (3 Common Road)",
84:"Cross Keys (32 Tadcaster Road)",
85:"Cross Keys (34 Goodramgate)",
86:"Cross Keys Hotel (89 Market Street)",
87:"Cross Keys Inn (Cawood Road)",
88:"Crown and Cushion (Welburn)",
89:"Crown Hotel (Horsefair)",
90:"Crown Inn, The (Bolton Percy)",
91:"Crown Inn, The (The Street)",
92:"Crystal Palace, The (66-68 Holgate Road)",
93:"Cut & Craft (8 St Sampsons Square)",
94:"Dawnay Arms (Newton on Ouse)",
95:"Dawnay Arms, The (Main Street)",
96:"Dean Court Hotel (Duncombe Place)",
97:"Deramore Arms, The (Main Street)",
98:"Derwent Arms, The (39 The Village)",
99:"Dick Turpin Inn, The (49 Moorcroft Road)",
100:"Dormouse, The (84 Shipton Road)",
101:"Drawing Board, The (10a New Street)",
102:"Duke of York (3-4 King's Square)",
103:"Duke of York (A166)",
104:"Duke of York, The (Station Road)",
105:"Dunsforth, The (Lower Dunsford)",
106:"Durham Ox, The (West Way)",
107:"Dusk (8 New Street)",
108:"D'vine (20-24 Swinegate)",
109:"Eagle & Child, The (9 High Petergate)",
110:"Ebor Inn, The (Main Street)",
111:"Edinburgh Arms (25 Fishergate)",
112:"Evil Eye Lounge (42 Stonegate)",
113:"Exhibition, The (19 Bootham)",
114:"Fairfax Arms (Main Street)",
115:"Fat Abbot, The (Main Street)",
116:"Fauconberg Arms (Coxwold)",
117:"Feathers Hotel, The (6 Market Place)",
118:"Feathers Hotel, The (Market Place)",
119:"Feversham Arms Hotel, The (2 High Street)",
120:"Feversham Arms Inn (Upper Farndale)",
121:"Flares (6 Tanner Row)",
122:"Fleece Inn, The (47 Main Street)",
123:"Flying Legends (Sterling Road)",
124:"Forresters Arms, The (The Square)",
125:"Fossgate Social, The (25 Fossgate)",
126:"Fossgate Tap, The (54-56 Fossgate)",
127:"Four Alls, The (Malton Road)",
128:"Fox & Hounds (Back Lane)",
129:"Fox & Hounds Country Inn (Main Street)",
130:"Fox and Roman, The (Tadcaster Road)",
131:"Fox Inn, The (90 The Village)",
132:"Fox, The (168 Holgate Road)",
133:"Fulford Arms (121 Fulford Road)",
134:"Gait Inn, The (Main Street)",
135:"George & Dragon Hotel, The (17 Market Place)",
136:"George, The (Market Place)",
137:"Gibson's (129 Micklegate)",
138:"Gillygate, The (48 Gillygate)",
139:"Gnu Inn, The (The Green)",
140:"Golden Ball (2 Cromwell Road)",
141:"Golden Fleece (16 Pavement)",
142:"Golden Lion Inn (Main Street)",
143:"Golden Lion, The (9 Church Street)",
144:"Golden Slipper, The (20 Goodramgate)",
145:"Goodmanham Arms (Main Street)",
146:"Graduate, The (6-12 Lendal)",
147:"Grantham Arms, The (Milby)",
148:"Grapes Inn (Railway Street)",
149:"Green Tree Inn (Boroughbridge Road)",
150:"Green Tree Inn, The (Beckfield Lane)",
151:"Grey Horse, The (Main Street)",
152:"Grey Horse, The (Main Street)",
153:"Greyhound Inn (82 Main Street)",
154:"Griffin Inn, The (74 Market Place)",
155:"Gusto (2-4 Little Stonegate)",
156:"Guy Fawkes Inn, The (25 High Petergate)",
157:"Habit, The (40 Goodramgate)",
158:"Half Moon (3 The Village)",
159:"Half Moon Inn, The (39 High Street)",
160:"Half Moon Inn, The (Main Street)",
161:"Hare & Hounds (8 Silver Street)",
162:"Hare & Hounds Inn (57 High Street)",
163:"Harkers (1 St Helens Square)",
164:"Harvester Clifton Moor (Stirling Road)",
165:"Heworth Inn (64 Heworth Green)",
166:"Highwayman, The (Finkle Street)",
167:"Hogs Head, The (Huntington Road)",
168:"Hole in the Wall, The (10 High Petergate)",
169:"Hop, The (11-12 Fossgate)",
170:"Horseshoe (Long Street)",
171:"Hotham Arms (20 Main Street)",
172:"House of the Trembling Madness (14 Lendal)",
173:"House of the Trembling Madness (48 Stonegate)",
174:"Hovingham Inn, The (Main Street)",
175:"Inn On The Green, The (3 The Green)",
176:"Jefferson Arms, The (Main Street)",
177:"Judge's Lodgings (9 Lendal)",
178:"Judson's (4 Market Place)",
179:"Kennedy's (1 Little Stonegate)",
180:"Keystones, The (4 Monkgate)",
181:"King William, The (Barkston Avenue)",
182:"Kings Arms (Kings Staith)",
183:"Kings Head (5 High Market Place)",
184:"Knavesmire, The (Albemarle Road)",
185:"Lamb & Lion, The (4 High Petergate)",
186:"Las Iguanas (21 Back Swinegate)",
187:"Last Drop Inn, The (27 Colliergate)",
188:"Leeman Rose, The (Stamford Street East)",
189:"Lendal Cellars (26 Lendal)",
190:"Lighthorseman (124 Fulford Road)",
191:"Lil's Bar (7 Kings Staith)",
192:"Lion Inn (Blakey Ridge)",
193:"Longboat, The (26 Blossom Street)",
194:"Lord Collingwood Inn (The Green)",
195:"Lord Nelson, The (9 Main Street)",
196:"Lowther, The (8 Cumberland Street)",
197:"Lucia (13 Swinegate Court East)",
198:"Lysander Arms (Shipton Road)",
199:"Macumba (3 Coffee Yard)",
200:"Maltings, The (Tanners Moat)",
201:"Marcia Grey, The (Front Street)",
202:"Marcia Inn, The (29 Main Street)",
203:"Market Cat, The (6 Jubbergate)",
204:"Market Tap, The (11-13 Market Place)",
205:"Mason's (13 Fossgate)",
206:"Masons Arms (6 Fishergate)",
207:"Melbourne Arms, The (The Barn)",
208:"Mended Drum, The (Tollerton Road)",
209:"Micklegate at 127, The (125-127 Micklegate)",
210:"Micklegate Social (148 Micklegate)",
211:"Middleton's (Skeldergate)",
212:"Millfield, The (White Rose Close)",
213:"Minster Inn (24 Marygate)",
214:"Mitre, The (Shipton Road)",
215:"Moors Inn, The (Headlands Road)",
216:"Mount, The (72 The Mount)",
217:"Murton Arms (Murton Lane)",
218:"Nags Head, The (100 Micklegate)",
219:"Nags Head, The (139 Main Street)",
220:"Nag's Head, The (56 Heworth Road)",
221:"New Inn (62 Long Street)",
222:"New Inn, The (Main Street)",
223:"New Inn, The (The Square)",
224:"No.88 Walmgate (Hotel Indigo) (88-96 Walmgate)",
225:"Nook, The (3a Castlegate)",
226:"Oak Tree Inn, The (Raskelf Road)",
227:"Oddfellows Arms, The (Main Street)",
228:"Old Black Bull, The (North End)",
229:"Old Ebor, The (99 Nunnery Lane)",
230:"Old Grey Mare, The (Clifton Green)",
231:"Old White Swan, The (80 Goodramgate)",
232:"O'Neill's (10 Low Ousegate)",
233:"Oscars (27 Swinegate)",
234:"Pairings (28 Castlegate)",
235:"Park Inn (North Street)",
236:"Pavement Vaults (2 Piccadilly)",
237:"Pear Tree Farm (North Business Park)",
238:"Pheasant Hotel, The (Mill Street)",
239:"Phoenix Inn, The (75 George Street)",
240:"Piccadilly Tap (Spark, 17-21 Piccadilly)",
241:"Pitcher and Piano (Coney Street)",
242:"Pivni (Patrick Pool)",
243:"Plonkers (5 Cumberland Street)",
244:"Plough Inn, The (Main Street)",
245:"Plough Inn, The (Main Street)",
246:"Plough Inn, The (Main Street)",
247:"Plough, The (48 Main Street)",
248:"Plum & Partridge (Low Street)",
249:"Popworld (George Hudson Street)",
250:"Postern Gate (JD Wetherspoon), The (90 Piccadilly)",
251:"Priory, The (103 Micklegate)",
252:"Punch Bowl (7 Stonegate)",
253:"Punch Bowl (JD Wetherspoon), The (5-9 Blossom Street)",
254:"Punch Bowl Inn, The (Marton)",
255:"Punch Bowl, The (134 Lowther Street)",
256:"Quaker Wood Inn, The (Acomb Wood Drive)",
257:"Red Lion (1 Finkle Street)",
258:"Red Lion Inn (52 The Village)",
259:"Red Lion, The (Boroughbridge Road)",
260:"Red Lion, The (Main St)",
261:"Red Lion, The (Merchant Gate)",
262:"Revolution (Coney Street)",
263:"Riverside Farm Pub, The (Shipton Road)",
264:"Roebuck Inn (Main Street)",
265:"Roman Bath (9 Saint Sampsons Square)",
266:"Rook & Gaskill (12 Lawrence Street)",
267:"Rose & Crown (13 Lawrence Street)",
268:"Rose & Crown (Main Street)",
269:"Rose & Crown (Simpson Hill)",
270:"Rose and Crown, The (Main Street)",
271:"Royal Oak (18 Goodramgate)",
272:"Royal Oak Hotel, The (Market Place)",
273:"Royal Oak Inn, The (Main Street)",
274:"Royal Oak, The (1 Main Street)",
275:"Saddle Inn, The (37 Main Street)",
276:"Sea Horse Hotel (4 Fawcett Street)",
277:"Ship Inn (Moor End)",
278:"Ship Inn, The (Low Road)",
279:"Ship, The (23 The Village)",
280:"Shoulder Of Mutton (Chapel Green)",
281:"Simply JJ's (63 Market Street)",
282:"Six Bells (Oxcarr Lane)",
283:"Slip Inn, The (20 Clementhorpe)",
284:"Slug & Lettuce, The (22-26 Back Swinegate)",
285:"Slug & Lettuce, The (1/1a Low Ousegate)",
286:"Snickleway Inn, The (47 Goodramgate)",
287:"Society (1 Rougier Street)",
288:"Sotano",
289:"Spotted Ox (Westfield Road)",
290:"Spread Eagle, The (98 Walmgate)",
291:"St Vincent Arms (Main Street)",
292:"St. Clement's Working Men's Club (Count De Burgh Terrace, South Bank)",
293:"Stapylton Arms, The (Hambleton Lane)",
294:"Star Inn (High Street)",
295:"Star Inn The City, The (Lendal Engine House, Museum Street)",
296:"Star, The (King Street)",
297:"Station Hotel, The (1 Pavement)",
298:"Station Inn (Station Road)",
299:"Stone Roses Bar, The (4 King Street)",
300:"Stone Trough Inn (Kirkham Abbey)",
301:"Stonegate Yard (8-10 Little Stonegate)",
302:"Summat's Brewing (18 Bridge Street)",
303:"Sun Inn (York Road)",
304:"Sun Inn, The (35 The Green)",
305:"Sun Inn, The (Normanby)",
306:"Swan, The (16 Bishopgate Street)",
307:"Tank & Paddle (1 Bridge Street)",
308:"Tap Room, The (Brewery Centre, Toft Green)",
309:"Terrace, The (5 Fossgate)",
310:"Theatre Royal (St. Leonard's Place)",
311:"Thirteen Thirty One (13 Grape Lane)",
312:"Thomas's of York (3 Museum Street)",
313:"Thompsons Arms (Flaxton Station)",
314:"Three Cranes (11 St Sampsons Square)",
315:"Three Cups (York Road)",
316:"Three Hares Inn (Main Street)",
317:"Three Horse Shoes (Bridge Street)",
318:"Three Tuns, The (12 Coppergate)",
319:"Three-Legged Mare, The (15 High Petergate)",
320:"Tiger 10 (St. Johns Church, Micklegate)",
321:"Tiger Inn, The (29 The Village)",
322:"Tiger Inn, The (The Green)",
323:"Toby Carvery Hopgrove (Malton Road)",
324:"Trafalgar Bay, The (7 Nunnery Lane)",
325:"Turtle Bay (11 Little Stonegate)",
326:"Vahe (Goodramgate)",
327:"Valhalla (4 Patrick Pool)",
328:"Victor J's (1a Finkle Street)",
329:"Victoria Vaults, The (49 Nunnery Lane)",
330:"Victoria, The (1 Heslington Road)",
331:"Victoria, The (Station Road)",
332:"Volunteer Arms (Watson Street)",
333:"Vudu Lounge (37-39 Swinegate)",
334:"Waggon & Horses (19 Lawrence Street)",
335:"Walmgate Ale House, The (25 Walmgate)",
336:"Walnut Tree (73 Heworth Village)",
337:"Watergate Inn, The (Walmgate)",
338:"Wellington Inn, The (47 Alma Terrace)",
339:"Wellington Oak (Canal Head)",
340:"Wenlock Arms (73 Main Street)",
341:"Whippet Inn, The (15 North Street)",
342:"White Bear (Main Street)",
343:"White Goose, The (30 Market Place)",
344:"White Horse (The Green)",
345:"White Horse Inn, The (West End)",
346:"White Horse, The (6 Bootham)",
347:"White Swan (Low Street)",
348:"White Swan, The (A19)",
349:"White Swan, The (Church Street)",
350:"White Swan, The (East End)",
351:"Wild Swan, The (Main Street)",
352:"Wilde's Wine Bar (21 Grape Lane)",
353:"Windmill, The (14-16 Blossom Street)",
354:"Winning Post, The (127-129 Bishopthorpe Road)",
355:"Wolds Inn, The (Driffield Road)",
356:"Woodman Inn, The (16 Main Street)",
357:"Worsley Arms Hotel (High Street)",
358:"Yates's (1 Church Lane)",
359:"Ye Old Shambles Tavern (44 Shambles)",
360:"Ye Olde Red Lion Hotel (25 Old Road)",
361:"Ye Olde Starre Inne (40 Stonegate)",
362:"York Tap (Station Concourse)",
363:"York, The (Market Place)",
364:"Yorkshire Bar @ The Monkbar Hotel (St Maurice's Road)"}

for number in pub:
    x = randrange(365)
    if x == number:
        y = pub[number]
        print (y)
        try_again = input('Try again? ')
        if try_again == 'yes':
            for number in pub:
                a = randrange(365)
                if a == number:
                    y = pub[number]
                    print(y)
                    try_again = input('Try again? ')
                    if try_again == 'yes':
                        for number in pub:
                            b = randrange(365)
                            if b == number:
                                y = pub[number]
                                print(y)
                                try_again = input('Try again? ')
                                if try_again == 'yes':
                                    for number in pub:
                                        c = randrange(365)
                                        if c == number:
                                            y = pub[number]
                                            print(y)